### ISSUE TITLE
Can someone explains about the callback parameter?

### ISSUE THREAD

**Issue by nhan14t1** [FYLSunghwan/react-native-pitch-tracker#12]
What is the parameter in "Note On: 60"??

**Comment by FYLSunghwan** [comment]
Hi Nhan,

The "MIDI Note number" is the number of MIDI described in here:
https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies

e.g., C4 is 60.

Closing Issue :)
